apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: aroprivilegednamespace
  annotations:
    metadata.gatekeeper.sh/title: "Privileged Namespace"
    metadata.gatekeeper.sh/version: 1.0.0
    description: >-
      Disallows creating, updating or deleting resources in privileged namespaces.
      including, ["^kube.*|^openshift.*|^default$|^redhat.*|^com$|^io$|^in$"]
spec:
  crd:
    spec:
      names:
        kind: AROPrivilegedNamespace
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          description: >-
            Disallows creating, updating or deleting resources in privileged namespaces.
            including, ["^kube.*|^openshift.*|^default$|^redhat.*|^com$|^io$|^in$"]
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package aroprivilegednamespace

        violation[{"msg": msg, "details": {}}] {
          input_priv_namespace(input.review.object.metadata.namespace)
          msg := sprintf("Operation in privileged namespace %v is not allowed", [input.review.object.metadata.namespace])
        }

        input_priv_namespace(ns) {
          any([ns == "default",
          ns == "com",
          ns == "io",
          ns == "in",
          startswith(ns, "openshift"),
          startswith(ns, "kube"),
          startswith(ns, "redhat")])
        }
